services:
  dvwa:
    build:
      context: .
      dockerfile: Dockerfile.php74
    image: dvwa-php74
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    networks:
      - dvwa
    ports:
      - "192.168.0.192:4280:80"
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=admin
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

volumes:
  dvwa:

networks:
  dvwa:
